# `U` is a predefined unit of measure that means 19.05mm, which is MX spacing
# cx and cy used for Kailh switches
units:
  px: cx + 3
  py: cy + 3
points:
  zones:
    matrix:
      anchor.shift: [160, -170]
      key:
        padding: 1cy
        spread: 1cx
      columns:
        pinky:
          rows:
            bottom.skip: true
            top.skip: true
            home.column_net: P5
        ring:
          rows:
            top.column_net: P2
            home.column_net: P4
            bottom.column_net: P9
          key.stagger: 0.3cy
        middle:
          rows:
            top.column_net: P0
            home.column_net: P3
            bottom.column_net: P8
          key.stagger: 0.15cy
        index:
          rows:
            top.column_net: P1
            home.column_net: P10
            bottom.column_net: P16
          key.stagger: 0.15cy
        inner:
          rows:
            top.column_net: P14
            home.column_net: P15
            bottom.column_net: P18
          key:
            stagger: -0.15cy
            splay: -1
            spread: cx + .3
        innerReach:
          key.stagger: -0.35cy
          rows:
            home.column_net: P19
            bottom.skip: true
            top.skip: true
      rows:
        bottom.padding: cy
        home.padding: cy
        top.padding: cy
    thumb:
      anchor:
        ref: matrix_inner_bottom
        shift: [1.08cx, -1.2cy]
        rotate: -3
      columns:
        tucky:
          key.name: thumb_tucky
          rows.thumb_tucky.column_net: P20
        reachy:
          key.width: cx
          key.spread: cx
          key.splay: -15
          key.shift: [0.15cx,-3]
          key.name: thumb_reachy
          rows.reachy.column_net: P21
outlines:
  raw:
    - what: rectangle
      where: true
      size: [cx, cy]
  keys:
    - what: rectangle
      where: true
      size: [cx-0.5,cy-0.5]
  board:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_pinky_home
          shift: [-0.5px, -0.5py]
        - ref: matrix_pinky_home
          shift: [-0.5px, 0.5py]
        - ref: matrix_pinky_home
          shift: [0.35px, 0.5py]
        - ref: matrix_ring_top
          shift: [-0.5px, 0.5py]
        - ref: matrix_middle_top
          shift: [-0.5px, 0.5py]
        - ref: matrix_index_top
          shift: [-0.5px, 0.5py]
        - ref: matrix_index_top
          shift: [0.5px, 0.5py]
        - ref: matrix_inner_top
          shift: [0.5px, 0.5py]
        - ref: matrix_innerReach_home
          shift: [-0.35px, 0.5py]
        - ref: matrix_innerReach_home
          shift: [1.62px, 0.5py]
        - ref: thumb_reachy
          shift: [0.5px, 0.5py]
        - ref: thumb_reachy
          shift: [0.5px, -0.5py]
        - ref: thumb_reachy
          shift: [-0.5px, -0.5py]
        - ref: thumb_tucky
          shift: [-0.5px, -0.5py]
        - ref: thumb_tucky
          shift: [-0.5px, 0.5py]
        - ref: matrix_inner_bottom
          shift: [-0.5px, -0.5py]
        - ref: matrix_middle_bottom
          shift: [0.5px, -0.5py]
        - ref: matrix_ring_bottom
          shift: [0.5px, -0.5py]
        - ref: matrix_ring_bottom
          shift: [-0.5px, -0.5py]
        - ref: matrix_pinky_home
          shift: [0.35px, -0.5py]
      fillet: 4

  combo:
      - name: board
      - operation: subtract
        name: keys
pcbs:
  custom_split:
    outlines:
      main:
        outline: board
    footprints:
      choc_hotswap:
        what: choc
        where: true
        params:
          keycaps: true
          reverse: true
          hotswap: true
          from: "{{column_net}}"
          to: GND
      choc_through_holes:
        what: choc
        where: true
        params:
          keycaps: true
          reverse: true
          from: "{{column_net}}"
          to: GND
      promicro:
        what: promicro
        params:
          orientation: "up"
        where:
          ref: matrix_innerReach_home
          rotate: -90
          shift: [1px,-0.45py]
      reset:
        what: button
        params:
          from: GND
          to: RST
        where:
          ref: matrix_innerReach_home
          shift: [0, -1]
          rotate: -90
      battery:
        what: jstph
        params:
          pos: VCC
          neg: GND
        where:
          ref: matrix_innerReach_home
      switch:
        what: slider
        params: 
          from: GND
          to: VCC
        where:
          ref:
            matrix_innerReach_home