# `U` is a predefined unit of measure that means 19.05mm, which is MX spacing
# cx and cy used for Kailh switches
units:
  px: cx + 3
  py: cy + 3
  dpx: cx + 6
  dpy: cy + 6
  screwSize: 1.5
  standoffSize: 2.5
points:
  zones:
    matrix:
      anchor.shift: [160, -170]
      key:
        padding: 1cy
        spread: 1cx
      columns:
        pinky:
          rows:
            bottom.skip: true
            top.skip: true
            home.column_net: P5
        ring:
          rows:
            top.column_net: P2
            home.column_net: P4
            bottom.column_net: P9
          key.stagger: 0.3cy
        middle:
          rows:
            top.column_net: P0
            home.column_net: P3
            bottom.column_net: P8
          key.stagger: 0.15cy
        index:
          rows:
            top.column_net: P1
            home.column_net: P10
            bottom.column_net: P16
          key.stagger: 0.15cy
        inner:
          rows:
            top.column_net: P14
            home.column_net: P15
            bottom.column_net: P18
          key:
            stagger: -0.15cy
            splay: -1
            spread: cx + .3
        innerReach:
          key.stagger: -0.35cy
          rows:
            home.column_net: P19
            bottom.skip: true
            top.skip: true
      rows:
        bottom.padding: cy
        home.padding: cy
        top.padding: cy
    thumb:
      anchor:
        ref: matrix_inner_bottom
        shift: [1.08cx, -1.2cy]
        rotate: -3
      columns:
        tucky:
          key.name: thumb_tucky
          rows.thumb_tucky.column_net: P20
        reachy:
          key.width: cx
          key.spread: cx
          key.splay: -15
          key.shift: [0.15cx,-3]
          key.name: thumb_reachy
          rows.reachy.column_net: P21
outlines:
  raw:
    - what: rectangle
      where: true
      size: [cx, cy]
  keys:
    - what: rectangle
      where: true
      size: [cx-0.5,cy-0.5]
  board:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_pinky_home
          shift: [-0.5px, -0.5py]
        - ref: matrix_pinky_home
          shift: [-0.5px, 0.5py]
        - ref: matrix_pinky_home
          shift: [0.35px, 0.5py]
        - ref: matrix_ring_top
          shift: [-0.5px, 0.5py]
        - ref: matrix_middle_top
          shift: [-0.5px, 0.5py]
        - ref: matrix_index_top
          shift: [-0.5px, 0.5py]
        - ref: matrix_index_top
          shift: [0.5px, 0.5py]
        - ref: matrix_inner_top
          shift: [0.5px, 0.5py]
        - ref: matrix_innerReach_home
          shift: [-0.35px, 0.54py]
        - ref: matrix_innerReach_home
          shift: [1.62px, 0.54py]
        - ref: thumb_reachy
          shift: [0.5px, 0.5py]
        - ref: thumb_reachy
          shift: [0.5px, -0.5py]
        - ref: thumb_reachy
          shift: [-0.5px, -0.5py]
        - ref: thumb_tucky
          shift: [-0.5px, -0.5py]
        - ref: thumb_tucky
          shift: [-0.5px, 0.5py]
        - ref: matrix_inner_bottom
          shift: [-0.5px, -0.5py]
        - ref: matrix_middle_bottom
          shift: [0.5px, -0.5py]
        - ref: matrix_ring_bottom
          shift: [0.5px, -0.5py]
        - ref: matrix_ring_bottom
          shift: [-0.5px, -0.5py]
        - ref: matrix_pinky_home
          shift: [0.35px, -0.5py]
      fillet: 4
  xlboard:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_pinky_home
          shift: [-0.5dpx, -0.5dpy]
        - ref: matrix_pinky_home
          shift: [-0.5dpx, 0.5dpy]
        - ref: matrix_pinky_home
          shift: [0.35dpx, 0.5dpy]
        - ref: matrix_ring_top
          shift: [-0.5dpx, 0.5dpy]
        - ref: matrix_middle_top
          shift: [-0.5dpx, 0.5dpy]
        - ref: matrix_index_top
          shift: [-0.5dpx, 0.5dpy]
        - ref: matrix_index_top
          shift: [0.5dpx, 0.5dpy]
        - ref: matrix_inner_top
          shift: [0.5dpx, 0.5dpy]
        - ref: matrix_innerReach_home
          shift: [-0.35dpx, 0.54dpy]
        - ref: matrix_innerReach_home
          shift: [1.62dpx, 0.54dpy]
        - ref: thumb_reachy
          shift: [0.5dpx, 0.5dpy]
        - ref: thumb_reachy
          shift: [0.5dpx, -0.5dpy]
        - ref: thumb_reachy
          shift: [-0.5dpx, -0.5dpy]
        - ref: thumb_tucky
          shift: [-0.5dpx, -0.5dpy]
        - ref: thumb_tucky
          shift: [-0.5dpx, 0.5dpy]
        - ref: matrix_inner_bottom
          shift: [-0.5dpx, -0.5dpy]
        - ref: matrix_middle_bottom
          shift: [0.5dpx, -0.5dpy]
        - ref: matrix_ring_bottom
          shift: [0.5dpx, -0.5dpy]
        - ref: matrix_ring_bottom
          shift: [-0.5dpx, -0.5dpy]
        - ref: matrix_pinky_home
          shift: [0.35dpx, -0.5dpy]
      fillet: 4
  combo:
      - name: board
      - operation: subtract
        name: keys
  mounting:
    - what: circle
      radius: screwSize
      where:
          ref: matrix_pinky_home
          shift: [0.55cx, -0.19cy]
    - what: circle
      radius: screwSize
      where:
          ref: matrix_inner_top
          shift: [-0.42cx, 0.55cy]
    - what: circle
      radius: screwSize
      where:
          ref: matrix_inner_bottom
          shift: [0.55cx, -0.5cy]
  standoff:
    - what: circle
      radius: standoffSize
      where:
          ref: matrix_pinky_home
          shift: [0.55cx, -0.19cy]
    - what: circle
      radius: standoffSize
      where:
          ref: matrix_inner_top
          shift: [-0.42cx, 0.55cy]
    - what: circle
      radius: standoffSize
      where:
          ref: matrix_inner_bottom
          shift: [0.55cx, -0.5cy]
pcbs:
  custom_split:
    outlines:
      main:
        outline: 
          board
    footprints:
      choc_hotswap:
        what: choc
        where: true
        params:
          reverse: true
          hotswap: true
          from: "{{column_net}}"
          to: GND
#      choc_through_holes:
#        what: choc
#        where: true
#        params:
#          keycaps: true
#          reverse: true
#          from: "{{column_net}}"
#          to: GND
      promicro:
        what: promicro
        params.orientation: "down"
        where:
          ref: matrix_innerReach_home
          rotate: -90
          shift: [1.085cx,-0.445cy]
      reset:
        what: button
        params:
          from: GND
          to: RST
        where:
          ref: matrix_innerReach_home
          shift: [1.745cx, -1.47cy]
          rotate: 90
      switch:
        what: slider
        params: 
          from: GND
          to: VCC
        where:
          ref: matrix_innerReach_home
          shift: [1.8cx, 0cy]
          rotate: -90
      holeMidLeft:
        what: mountinghole
        where:
          ref: matrix_pinky_home
          shift: [0.55cx, -0.19cy]
      holeTopRight:
        what: mountinghole
        where:
          ref: matrix_inner_top
          shift: [-0.42cx, 0.55cy]
      holeBottomMid:
        what: mountinghole
        where:
          ref: matrix_inner_bottom
          shift: [0.55cx, -0.5cy]
      connector:
        what: jstph
        params:
          pos: RAW
          neg: GND
        where:
          ref: matrix_innerReach_home
          shift: [0.3cx, -0.70cy]
cases:
  bottom:
    - name: board
      extrude: 1
  xlbottom:
    - name: xlboard
      extrude: 1
  _outerwall:
    - name: xlboard
      extrude: 4
  _innerwall:
    - name: board
      extrude: 4
  wall:
    - what: case
      name: _outerwall
      operation: add
    - what: case
      name: _innerwall
      operation: subtract
  _holes:
    - name: mounting
      extrude: 4
  _standoffs:
    - name: standoff
      extrude: 4
  case:
    - what: case
      name: _standoffs
      operation: add
    - what: case
      name: _holes
      operation: subtract
    - what: case
      name: xlbottom
      operation: add
    - what: case
      name: wall
      operation: add